name: Android

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: pod install
      working-directory: ios
      name: Install pod dependencies

    - name: Build iOS (debug)
      run: "xcodebuild \
        -workspace ios/ChessClub.xcworkspace \
        -scheme ChessClub \
        clean archive \
        -sdk iphoneos \
        -configuration Debug \
        -UseModernBuildSystem=NO \
        -archivePath $PWD/ChessClub \
        CODE_SIGNING_ALLOWED=NO"

    - name: Compress .xcarchive
      run: zip -r -9 ChessClub.xcarchive.zip $PWD/ChessClub.xcarchive/

    - uses: actions/upload-artifact@v2
      with:
        name: ios-xarchive
        path: ChessClub.xcarchive.zip
